

USE SOCIALNETWORK ;
DROP TABLE IF EXISTS FOLLOWERS ;

CREATE TABLE FOLLOWERS(
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
FOLLOWER_ID INT NOT NULL,
    FOREIGN KEY (FOLLOWER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    PRIMARY KEY(USER_ID, FOLLOWER_ID)
) ENGINE=INNODB;