USE SOCIALNETWORK ;
DROP TABLE IF EXISTS USERS ;

CREATE TABLE USERS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) not null,
    NICK VARCHAR(50) NOT NULL UNIQUE ,
    EMAIL VARCHAR(50) NOT NULL  ,
    PASSWORD VARCHAR(20) NOT NULL  ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;
